# This is a basic workflow to help you get started with MATLAB Actions

name: MATLAB Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        case: [1,2,3,4,5,6,7,8,9,10,11,12] #,13]
         
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Sets up MATLAB on a GitHub-hosted runner
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      # You can use "run-build" to invoke the MATLAB build tool and run build tasks
      #- name: Run the default "test" task in the build file
      #   uses: matlab-actions/run-build@v1

      # You can use "run-command" to execute custom MATLAB scripts, functions, or statements
      - name: Make Results folder
        run: mkdir -p Results/case_${{ matrix.case }}
  
      - name: Run VC
        uses: matlab-actions/run-command@v1
        with:
          command: |
            vcdir = fullfile(pwd, 'code', 'VC_v1p1');
            addpath(genpath(vcdir));
            cd(vcdir);

            try
                run_VC_bench(${{ matrix.case }});
            catch ME
                disp(getReport(ME, 'extended'));
                exit(1);
            end
  Tests:
    runs-on: ubuntu-latest
    needs: build
    steps:

    
      - name: Upload VC results
        uses: actions/upload-artifact@v3
        with:
          name: vc-results-${{ matrix.case }}
          path: code/VC_v1p1/results/case_${{ matrix.case }}/simdata.mat

      - name: Download VC results
        uses: actions/download-artifact@v3
        with:
          name: vc-results-${{ matrix.case }}
          path: code/tests/downloaded_results


      - name: Run Validation Test
        uses: matlab-actions/run-command@v1
        with:
          command: |
            addpath(genpath(fullfile(pwd,'code/tests')));
            cd(fullfile(pwd,'code/tests'));
            setenv('MATRIX_CASE','${{ matrix.case }}');
            runtests('validate_sim_results');

         
            
      - name: Debug Results
        run: |
               pwd
               ls -lah
               ls -lah Results || true
    
      - name: Upload simulation results
        uses: actions/upload-artifact@v4
        with:
          name: VC_results_case_${{ matrix.case }}
          path: Results/case_${{ matrix.case }} #VC_results_case_${{ matrix.case }}/


  merge-results:
    runs-on: ubuntu-latest
    needs: Tests
    steps:
      - name: Download all case artifacts
        uses: actions/download-artifact@v4
        with:
          path: all_results

      - name: Merge into single Results folder
        run: |
          mkdir -p Results
          mv all_results/* Results/

      - name: Upload combined results
        uses: actions/upload-artifact@v4
        with:
          name: VC_results_all_cases
          path: Results
  # Runs a set of commands using the runners shell
      #- name: Run all tests
        #uses: matlab-actions/run-tests@v2
        #with:
          #source-folder: code
          
  
